/****************************************************************************
**
** Metadata for DbCommOcxLibEF5 generated by dumpcpp v5.12.10 using
** dumpcpp {69E81D18-C1AC-448D-9EF1-60C32D40CF07}
** from the type library D:\Program Files (x86)\eForceCon V5.0\DbCommOcx.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_DBCOMMOCXLIBEF5_NOINLINES
#include "dbcommocxlibef5.h"

using namespace DbCommOcxLibEF5;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[96];
    char stringdata0[1226];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 31, 0),
QT_MOC_LITERAL(1, 32, 9, 0),
QT_MOC_LITERAL(2, 42, 0, 0),
QT_MOC_LITERAL(3, 43, 4, 0),
QT_MOC_LITERAL(4, 48, 6, 0),
QT_MOC_LITERAL(5, 55, 4, 0),
QT_MOC_LITERAL(6, 60, 4, 0),
QT_MOC_LITERAL(7, 65, 15, 0),
QT_MOC_LITERAL(8, 81, 4, 0),
QT_MOC_LITERAL(9, 86, 6, 0),
QT_MOC_LITERAL(10, 93, 4, 0),
QT_MOC_LITERAL(11, 98, 4, 0),
QT_MOC_LITERAL(12, 103, 8, 0),
QT_MOC_LITERAL(13, 112, 8, 0),
QT_MOC_LITERAL(14, 121, 8, 0),
QT_MOC_LITERAL(15, 130, 11, 0),
QT_MOC_LITERAL(16, 142, 7, 0),
QT_MOC_LITERAL(17, 150, 15, 0),
QT_MOC_LITERAL(18, 166, 8, 0),
QT_MOC_LITERAL(19, 175, 12, 0),
QT_MOC_LITERAL(20, 188, 12, 0),
QT_MOC_LITERAL(21, 201, 22, 0),
QT_MOC_LITERAL(22, 224, 9, 0),
QT_MOC_LITERAL(23, 234, 23, 0),
QT_MOC_LITERAL(24, 258, 7, 0),
QT_MOC_LITERAL(25, 266, 13, 0),
QT_MOC_LITERAL(26, 280, 12, 0),
QT_MOC_LITERAL(27, 293, 14, 0),
QT_MOC_LITERAL(28, 308, 13, 0),
QT_MOC_LITERAL(29, 322, 7, 0),
QT_MOC_LITERAL(30, 330, 9, 0),
QT_MOC_LITERAL(31, 340, 10, 0),
QT_MOC_LITERAL(32, 351, 9, 0),
QT_MOC_LITERAL(33, 361, 7, 0),
QT_MOC_LITERAL(34, 369, 10, 0),
QT_MOC_LITERAL(35, 380, 12, 0),
QT_MOC_LITERAL(36, 393, 11, 0),
QT_MOC_LITERAL(37, 405, 12, 0),
QT_MOC_LITERAL(38, 418, 17, 0),
QT_MOC_LITERAL(39, 436, 19, 0),
QT_MOC_LITERAL(40, 456, 17, 0),
QT_MOC_LITERAL(41, 474, 7, 0),
QT_MOC_LITERAL(42, 482, 11, 0),
QT_MOC_LITERAL(43, 494, 10, 0),
QT_MOC_LITERAL(44, 505, 9, 0),
QT_MOC_LITERAL(45, 515, 14, 0),
QT_MOC_LITERAL(46, 530, 12, 0),
QT_MOC_LITERAL(47, 543, 10, 0),
QT_MOC_LITERAL(48, 554, 10, 0),
QT_MOC_LITERAL(49, 565, 14, 0),
QT_MOC_LITERAL(50, 580, 8, 0),
QT_MOC_LITERAL(51, 589, 13, 0),
QT_MOC_LITERAL(52, 603, 10, 0),
QT_MOC_LITERAL(53, 614, 12, 0),
QT_MOC_LITERAL(54, 627, 11, 0),
QT_MOC_LITERAL(55, 639, 11, 0),
QT_MOC_LITERAL(56, 651, 9, 0),
QT_MOC_LITERAL(57, 661, 16, 0),
QT_MOC_LITERAL(58, 678, 6, 0),
QT_MOC_LITERAL(59, 685, 17, 0),
QT_MOC_LITERAL(60, 703, 15, 0),
QT_MOC_LITERAL(61, 719, 11, 0),
QT_MOC_LITERAL(62, 731, 14, 0),
QT_MOC_LITERAL(63, 746, 10, 0),
QT_MOC_LITERAL(64, 757, 19, 0),
QT_MOC_LITERAL(65, 777, 16, 0),
QT_MOC_LITERAL(66, 794, 7, 0),
QT_MOC_LITERAL(67, 802, 9, 0),
QT_MOC_LITERAL(68, 812, 10, 0),
QT_MOC_LITERAL(69, 823, 7, 0),
QT_MOC_LITERAL(70, 831, 13, 0),
QT_MOC_LITERAL(71, 845, 10, 0),
QT_MOC_LITERAL(72, 856, 19, 0),
QT_MOC_LITERAL(73, 876, 10, 0),
QT_MOC_LITERAL(74, 887, 7, 0),
QT_MOC_LITERAL(75, 895, 42, 0),
QT_MOC_LITERAL(76, 938, 9, 0),
QT_MOC_LITERAL(77, 948, 16, 0),
QT_MOC_LITERAL(78, 965, 11, 0),
QT_MOC_LITERAL(79, 977, 17, 0),
QT_MOC_LITERAL(80, 995, 16, 0),
QT_MOC_LITERAL(81, 1012, 12, 0),
QT_MOC_LITERAL(82, 1025, 16, 0),
QT_MOC_LITERAL(83, 1042, 29, 0),
QT_MOC_LITERAL(84, 1072, 17, 0),
QT_MOC_LITERAL(85, 1090, 20, 0),
QT_MOC_LITERAL(86, 1111, 11, 0),
QT_MOC_LITERAL(87, 1123, 9, 0),
QT_MOC_LITERAL(88, 1133, 11, 0),
QT_MOC_LITERAL(89, 1145, 10, 0),
QT_MOC_LITERAL(90, 1156, 10, 0),
QT_MOC_LITERAL(91, 1167, 16, 0),
QT_MOC_LITERAL(92, 1184, 12, 0),
QT_MOC_LITERAL(93, 1197, 7, 0),
QT_MOC_LITERAL(94, 1205, 12, 0),
QT_MOC_LITERAL(95, 1218, 6, 0)
    },
    "DbCommOcxLibEF5::_DDbCommOcxEF5\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0AboutBox\0AckAlarm\0QString&\0bstrAckUser\0vaAlmNo\0"
    "AddAlarmComment\0bstrUser\0vaAlmComment\0CloseConnect\0DelChangeTagParsByName\0"
    "vaTagName\0DelChangeTagParsByRegNo\0vaRegNo\0GetAlarmCount\0GetAlarmData\0"
    "GetAllTagCount\0GetAllTagName\0GetData\0GetDataEx\0GetHisData\0StartTime\0EndTime\0"
    "lDataCount\0GetHisDataEx\0GetHisTrace\0batrpTagName\0GetMarkupLayerStr\0"
    "bstrpMarkerLayerStr\0GetNodeAllTagName\0lAreaNo\0GetNodeInfo\0GetRegData\0GetStatus\0"
    "GetTagParCount\0bstrpTagName\0GetTagPars\0GetTagType\0GetTagTypePars\0lTagType\0"
    "InsertHisData\0vaDataTime\0vaDataTimeSh\0vaDataValue\0IsConnected\0IsWorking\0"
    "OpenLocalConnect\0bAsync\0OpenRemoteConnect\0bstrpRemoteAddr\0lRemotePort\0"
    "bstrpLocalAddr\0lLocalPort\0RemoveChangeTagPars\0SetChangeTagPars\0SetData\0"
    "vaTagData\0SetTimeOut\0TimeOut\0SetUpDateTime\0UpDateTime\0SubscribeAlmLogInfo\0"
    "bSubscribe\0control\0__MIDL___MIDL_itf_DbCommOcx_0000_0000_0001\0STATUS_OK\0"
    "STATUS_NOCONNECT\0STATUS_INIT\0STATUS_DISCONNECT\0STATUS_RECONNECT\0STATUS_NOLIC\0"
    "STATUS_INITFALSE\0DbCommOcxLibEF5::DbCommOcxEF5\0Event Interface 1\0"
    "_DDbCommOcxEventsEF5\0AlarmChange\0AlarmData\0lAlarmCount\0DataChange\0vaTagValue\0"
    "ReqAsyncComplate\0lComplateKey\0lStatus\0StatusChange\0Status\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_DbCommOcxLibEF5___DDbCommOcxEF5[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    40, 14, // methods
    3, 366, // properties
    1, 375, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 214, 2, 5,
    7, 1, 223, 2, 5,
    9, 3, 226, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 233, 2, 9,
    13, 2, 234, 2, 9,
    17, 3, 239, 2, 9,
    20, 0, 246, 2, 9,
    21, 1, 247, 2, 9,
    23, 1, 250, 2, 9,
    25, 0, 253, 2, 9,
    26, 0, 254, 2, 9,
    27, 0, 255, 2, 9,
    28, 0, 256, 2, 9,
    29, 1, 257, 2, 9,
    30, 1, 260, 2, 9,
    31, 4, 263, 2, 9,
    35, 4, 272, 2, 9,
    36, 3, 281, 2, 9,
    38, 1, 288, 2, 9,
    40, 1, 291, 2, 9,
    42, 1, 294, 2, 9,
    43, 1, 297, 2, 9,
    44, 0, 300, 2, 9,
    45, 1, 301, 2, 9,
    47, 1, 304, 2, 9,
    48, 1, 307, 2, 9,
    49, 1, 310, 2, 9,
    51, 4, 313, 2, 9,
    55, 0, 322, 2, 9,
    56, 0, 323, 2, 9,
    57, 0, 324, 2, 11,
    57, 1, 325, 2, 9,
    59, 4, 328, 2, 11,
    59, 5, 337, 2, 9,
    64, 0, 348, 2, 9,
    65, 1, 349, 2, 9,
    66, 2, 352, 2, 9,
    68, 1, 357, 2, 9,
    70, 1, 360, 2, 9,
    72, 1, 363, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, 0x80000000 | 14, QMetaType::QVariant, 15, 16,
    QMetaType::Int, 0x80000000 | 14, QMetaType::QVariant, QMetaType::QVariant, 18, 16, 19,
    QMetaType::Void,
    QMetaType::Int, QMetaType::QVariant, 22,
    QMetaType::Int, QMetaType::QVariant, 24,
    QMetaType::Int,
    QMetaType::QVariant,
    QMetaType::Int,
    QMetaType::QVariant,
    QMetaType::QVariant, QMetaType::QVariant, 22,
    QMetaType::QVariant, QMetaType::QVariant, 22,
    QMetaType::QVariant, QMetaType::QDateTime, QMetaType::QDateTime, QMetaType::Int, QMetaType::QVariant, 32, 33, 34, 22,
    QMetaType::QVariant, QMetaType::QDateTime, QMetaType::QDateTime, QMetaType::Int, QMetaType::QVariant, 32, 33, 34, 22,
    QMetaType::QVariant, QMetaType::QDateTime, QMetaType::QDateTime, 0x80000000 | 14, 32, 33, 37,
    QMetaType::Int, 0x80000000 | 14, 39,
    QMetaType::QVariant, QMetaType::Int, 41,
    QMetaType::QVariant, QMetaType::Int, 41,
    QMetaType::QVariant, QMetaType::QVariant, 22,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 14, 46,
    QMetaType::QVariant, 0x80000000 | 14, 46,
    QMetaType::Int, 0x80000000 | 14, 46,
    QMetaType::QVariant, QMetaType::Int, 50,
    QMetaType::Int, 0x80000000 | 14, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 46, 52, 53, 54,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, 58,
    QMetaType::Int, 0x80000000 | 14, QMetaType::Int, 0x80000000 | 14, QMetaType::Int, 60, 61, 62, 63,
    QMetaType::Int, 0x80000000 | 14, QMetaType::Int, 0x80000000 | 14, QMetaType::Int, QMetaType::Int, 60, 61, 62, 63, 58,
    QMetaType::Int,
    QMetaType::QVariant, QMetaType::QVariant, 22,
    QMetaType::Int, QMetaType::QVariant, QMetaType::QVariant, 22, 67,
    QMetaType::Void, QMetaType::Int, 69,
    QMetaType::Void, QMetaType::Int, 71,
    QMetaType::Int, QMetaType::Int, 73,

 // properties: name, type, flags
    69, QMetaType::Int, 0x02015003, 		 // int TimeOut
    71, QMetaType::Int, 0x02015003, 		 // int UpDateTime
    74, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    75, 0x0, 7, 379, 

 // enum data: key, value
    76, uint(DbCommOcxLibEF5::STATUS_OK),
    77, uint(DbCommOcxLibEF5::STATUS_NOCONNECT),
    78, uint(DbCommOcxLibEF5::STATUS_INIT),
    79, uint(DbCommOcxLibEF5::STATUS_DISCONNECT),
    80, uint(DbCommOcxLibEF5::STATUS_RECONNECT),
    81, uint(DbCommOcxLibEF5::STATUS_NOLIC),
    82, uint(DbCommOcxLibEF5::STATUS_INITFALSE),
    0 // eod
};

const QMetaObject _DDbCommOcxEF5::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DbCommOcxLibEF5___DDbCommOcxEF5, 0, 0, 0 }
};

void *_DDbCommOcxEF5::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DbCommOcxLibEF5::_DDbCommOcxEF5"))
        return static_cast<void*>(const_cast<_DDbCommOcxEF5*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DbCommOcxLibEF5__DbCommOcxEF5[] = {

 // content:
    7, // revision
    83,  // classname
    1, 14, // classinfo
    44, 16, // methods
    2, 410, // properties
    1, 416, // enums/sets
    0, 0, // constructors
    0, // flags
    7, // signal count

 // classinfo: key, value
    84, 85, 

// signal: name, argc, parameters, tag, flags
    86, 2, 236, 2, 5,
    89, 4, 241, 2, 5,
    91, 2, 250, 2, 5,
    94, 1, 255, 2, 5,
    1, 4, 258, 2, 5,
    7, 1, 267, 2, 5,
    9, 3, 270, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 277, 2, 9,
    13, 2, 278, 2, 9,
    17, 3, 283, 2, 9,
    20, 0, 290, 2, 9,
    21, 1, 291, 2, 9,
    23, 1, 294, 2, 9,
    25, 0, 297, 2, 9,
    26, 0, 298, 2, 9,
    27, 0, 299, 2, 9,
    28, 0, 300, 2, 9,
    29, 1, 301, 2, 9,
    30, 1, 304, 2, 9,
    31, 4, 307, 2, 9,
    35, 4, 316, 2, 9,
    36, 3, 325, 2, 9,
    38, 1, 332, 2, 9,
    40, 1, 335, 2, 9,
    42, 1, 338, 2, 9,
    43, 1, 341, 2, 9,
    44, 0, 344, 2, 9,
    45, 1, 345, 2, 9,
    47, 1, 348, 2, 9,
    48, 1, 351, 2, 9,
    49, 1, 354, 2, 9,
    51, 4, 357, 2, 9,
    55, 0, 366, 2, 9,
    56, 0, 367, 2, 9,
    57, 0, 368, 2, 11,
    57, 1, 369, 2, 9,
    59, 4, 372, 2, 11,
    59, 5, 381, 2, 9,
    64, 0, 392, 2, 9,
    65, 1, 393, 2, 9,
    66, 2, 396, 2, 9,
    68, 1, 401, 2, 9,
    70, 1, 404, 2, 9,
    72, 1, 407, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::QVariant, QMetaType::Int, 87, 88,
    QMetaType::Void, QMetaType::Int, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 34, 24, 22, 90,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 92, 93,
    QMetaType::Void, QMetaType::Int, 95,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, 0x80000000 | 14, QMetaType::QVariant, 15, 16,
    QMetaType::Int, 0x80000000 | 14, QMetaType::QVariant, QMetaType::QVariant, 18, 16, 19,
    QMetaType::Void,
    QMetaType::Int, QMetaType::QVariant, 22,
    QMetaType::Int, QMetaType::QVariant, 24,
    QMetaType::Int,
    QMetaType::QVariant,
    QMetaType::Int,
    QMetaType::QVariant,
    QMetaType::QVariant, QMetaType::QVariant, 22,
    QMetaType::QVariant, QMetaType::QVariant, 22,
    QMetaType::QVariant, QMetaType::QDateTime, QMetaType::QDateTime, QMetaType::Int, QMetaType::QVariant, 32, 33, 34, 22,
    QMetaType::QVariant, QMetaType::QDateTime, QMetaType::QDateTime, QMetaType::Int, QMetaType::QVariant, 32, 33, 34, 22,
    QMetaType::QVariant, QMetaType::QDateTime, QMetaType::QDateTime, 0x80000000 | 14, 32, 33, 37,
    QMetaType::Int, 0x80000000 | 14, 39,
    QMetaType::QVariant, QMetaType::Int, 41,
    QMetaType::QVariant, QMetaType::Int, 41,
    QMetaType::QVariant, QMetaType::QVariant, 22,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 14, 46,
    QMetaType::QVariant, 0x80000000 | 14, 46,
    QMetaType::Int, 0x80000000 | 14, 46,
    QMetaType::QVariant, QMetaType::Int, 50,
    QMetaType::Int, 0x80000000 | 14, QMetaType::QVariant, QMetaType::QVariant, QMetaType::QVariant, 46, 52, 53, 54,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, 58,
    QMetaType::Int, 0x80000000 | 14, QMetaType::Int, 0x80000000 | 14, QMetaType::Int, 60, 61, 62, 63,
    QMetaType::Int, 0x80000000 | 14, QMetaType::Int, 0x80000000 | 14, QMetaType::Int, QMetaType::Int, 60, 61, 62, 63, 58,
    QMetaType::Int,
    QMetaType::QVariant, QMetaType::QVariant, 22,
    QMetaType::Int, QMetaType::QVariant, QMetaType::QVariant, 22, 67,
    QMetaType::Void, QMetaType::Int, 69,
    QMetaType::Void, QMetaType::Int, 71,
    QMetaType::Int, QMetaType::Int, 73,

 // properties: name, type, flags
    69, QMetaType::Int, 0x02015003, 		 // int TimeOut
    71, QMetaType::Int, 0x02015003, 		 // int UpDateTime

 // enums: name, flags, count, data
    75, 0x0, 7, 420, 

 // enum data: key, value
    76, uint(DbCommOcxLibEF5::STATUS_OK),
    77, uint(DbCommOcxLibEF5::STATUS_NOCONNECT),
    78, uint(DbCommOcxLibEF5::STATUS_INIT),
    79, uint(DbCommOcxLibEF5::STATUS_DISCONNECT),
    80, uint(DbCommOcxLibEF5::STATUS_RECONNECT),
    81, uint(DbCommOcxLibEF5::STATUS_NOLIC),
    82, uint(DbCommOcxLibEF5::STATUS_INITFALSE),
    0 // eod
};

const QMetaObject DbCommOcxEF5::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DbCommOcxLibEF5__DbCommOcxEF5, 0, 0, 0 }
};

void *DbCommOcxEF5::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DbCommOcxLibEF5::DbCommOcxEF5"))
        return static_cast<void*>(const_cast<DbCommOcxEF5*>(this));
    return QAxWidget::qt_metacast(_clname);
}

